apiVersion: apps/v1
kind: Deployment
metadata:
  name: dixit-test-app
  labels:
    app: dixit-test-app
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dixit-test-app
  template:
    metadata:
      labels:
        app: dixit-test-app
        version: v1.0.0
    spec:
      containers:
      - name: dixit-test-app
        image: REPLACE_WITH_IMAGE_URI
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: APP_NAME
          value: "Dixit App (Kubernetes)"
        - name: APP_VERSION
          value: "1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
