apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-js-app
  template:
    metadata:
      labels:
        app: simple-js-app
    spec:
      containers:
      - name: simple-js-app
        image: REPLACE_WITH_IMAGE_URI
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
