apiVersion: v1
kind: Service
metadata:
  name: dixit-test-app-svc
  labels:
    app: dixit-test-app
    version: v1.0.0
spec:
  type: LoadBalancer
  selector:
    app: dixit-test-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
