name: Build & Deploy → EKS

permissions:
  id-token: write     # ← allows aws-actions/configure-aws-credentials to fetch the JWT :contentReference[oaicite:0]{index=0}
  contents: read      # ← lets you check out your code

on:
  push:
    branches: [ main ]

env:
  IMAGE_URI: ${{ secrets.ECR_REGISTRY }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region:     ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push image
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region:     ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks update-kubeconfig \
              --region ${{ secrets.AWS_REGION }} \
              --name   ${{ secrets.EKS_CLUSTER_NAME }}  :contentReference[oaicite:0]{index=0}

      - name: Deploy to EKS
        run: |
          sed -i "s|REPLACE_WITH_IMAGE_URI|$IMAGE_URI|g" k8s/deployment.yaml
          kubectl apply -f k8s/
          kubectl rollout status deployment/simple-js-app --namespace default