jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v4

      # Step 1: configure AWS via OIDC
      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region:     ${{ secrets.AWS_REGION }}

      # Step 2: echo the region (now that AWS_REGION is in env)
      - name: Debug: print AWS region
        run: echo "Running deployment in region $AWS_REGION"

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & push image
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region:     ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        uses: aws-actions/eks-kubeconfig@v2
        with:
          cluster-name: ${{ secrets.EKS_CLUSTER_NAME }}
          region:       ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          sed -i "s|REPLACE_WITH_IMAGE_URI|$IMAGE_URI|g" k8s/deployment.yaml
          kubectl apply -f k8s/
          kubectl rollout status deployment/simple-js-app --namespace default
